/**
 * Minimal dashboard for MCP-only installs.
 *
 * Without this, installing just the MCP server leaves you with working entities and
 * nowhere to see them: the rich `copilot-decisions` view is generated by the
 * PowerShell daemon, which an MCP-only user does not have.
 *
 * This deliberately writes a *separate* view (`copilot-mcp` by default) and never
 * touches `copilot-decisions`, so the two installs cannot fight over one dashboard.
 * The existing config is read and merged, so several MCP clients can each add their
 * own card without clobbering one another.
 */

import { entityIds } from './entities.js';

export const DEFAULT_URL_PATH = 'copilot-mcp';

function cardFor(node, title) {
  const ids = entityIds(node);
  return {
    type: 'entities',
    title,
    // Tagged so a later run can find and replace exactly this card.
    entities: [
      { entity: ids.status, name: 'Status' },
      { entity: ids.decision, name: 'Decision' },
      { entity: ids.reply, name: 'Reply' },
    ],
  };
}

export async function ensureDashboard(ha, node, title, urlPath = DEFAULT_URL_PATH) {
  const socket = await ha.connectSocket();
  try {
    let config = null;
    const existing = await socket.send({ type: 'lovelace/config', url_path: urlPath });
    if (existing.success) config = existing.result;

    if (!config) {
      // Creating the dashboard itself is a separate call from writing its config, and
      // it fails harmlessly if a previous run already made it.
      await socket.send({
        type: 'lovelace/dashboards/create',
        url_path: urlPath,
        title: 'Copilot MCP',
        icon: 'mdi:robot',
        show_in_sidebar: true,
        require_admin: false,
      });
      config = { views: [{ title: 'MCP', path: 'mcp', type: 'masonry', cards: [] }] };
    }

    const view = config.views?.[0] ?? { title: 'MCP', path: 'mcp', cards: [] };
    const others = (view.cards ?? []).filter(
      (card) => !JSON.stringify(card).includes(`${node}_decision`),
    );
    const merged = {
      ...config,
      views: [{ ...view, cards: [...others, cardFor(node, title)] }, ...(config.views?.slice(1) ?? [])],
    };

    const saved = await socket.send({
      type: 'lovelace/config/save',
      url_path: urlPath,
      config: merged,
    });
    return saved.success === true;
  } finally {
    socket.close();
  }
}

/** Drops this client's card when the session ends, leaving the view tidy. */
export async function removeFromDashboard(ha, node, urlPath = DEFAULT_URL_PATH) {
  const socket = await ha.connectSocket();
  try {
    const existing = await socket.send({ type: 'lovelace/config', url_path: urlPath });
    if (!existing.success || !existing.result?.views?.length) return false;

    const config = existing.result;
    const view = config.views[0];
    const cards = (view.cards ?? []).filter(
      (card) => !JSON.stringify(card).includes(`${node}_decision`),
    );
    if (cards.length === (view.cards ?? []).length) return false;

    await socket.send({
      type: 'lovelace/config/save',
      url_path: urlPath,
      config: { ...config, views: [{ ...view, cards }, ...config.views.slice(1)] },
    });
    return true;
  } finally {
    socket.close();
  }
}
