/**
 * Minimal dashboard for MCP-only installs.
 *
 * Without this, installing just the MCP server leaves you with working entities and
 * nowhere to see them: the rich `copilot-decisions` view is generated by the
 * PowerShell daemon, which an MCP-only user does not have.
 *
 * This deliberately writes a *separate* view (`copilot-mcp` by default) and never
 * touches `copilot-decisions`, so the two installs cannot fight over one dashboard.
 * The existing config is read and merged, so several MCP clients can each add their
 * own card without clobbering one another.
 */

import { entityIds } from './entities.js';

export const DEFAULT_URL_PATH = 'copilot-mcp';

function cardFor(node, title) {
  const ids = entityIds(node);
  return {
    type: 'entities',
    title,
    // Tagged so a later run can find and replace exactly this card.
    entities: [
      { entity: ids.status, name: 'Status' },
      { entity: ids.decision, name: 'Decision' },
      { entity: ids.reply, name: 'Reply' },
    ],
  };
}

export async function ensureDashboard(ha, node, title, urlPath = DEFAULT_URL_PATH) {
  const socket = await ha.connectSocket();
  try {
    // When the PowerShell daemon is installed it owns copilot-decisions and renders
    // every session it can see, including MCP clients, with a reduced card. Creating
    // a second dashboard in that case would put two sidebar entries in front of the
    // user for what is one feature, so this defers instead.
    const managed = await socket.send({ type: 'lovelace/config', url_path: 'copilot-decisions' });
    if (managed.success) return 'managed';

    let config = null;
    const existing = await socket.send({ type: 'lovelace/config', url_path: urlPath });
    if (existing.success) config = existing.result;

    if (!config) {
      // Creating the dashboard itself is a separate call from writing its config, and
      // it fails harmlessly if a previous run already made it.
      await socket.send({
        type: 'lovelace/dashboards/create',
        url_path: urlPath,
        title: 'Copilot MCP',
        icon: 'mdi:robot',
        show_in_sidebar: true,
        require_admin: false,
      });
      config = { views: [{ title: 'MCP', path: 'mcp', type: 'masonry', cards: [] }] };
    }

    const view = config.views?.[0] ?? { title: 'MCP', path: 'mcp', cards: [] };
    const others = (view.cards ?? []).filter(
      (card) => !JSON.stringify(card).includes(`${node}_decision`),
    );
    const merged = {
      ...config,
      views: [{ ...view, cards: [...others, cardFor(node, title)] }, ...(config.views?.slice(1) ?? [])],
    };

    const saved = await socket.send({
      type: 'lovelace/config/save',
      url_path: urlPath,
      config: merged,
    });
    return saved.success === true;
  } finally {
    socket.close();
  }
}

/**
 * Drops this client's card when the session ends, and removes the dashboard itself
 * once the last card is gone.
 *
 * Leaving an empty dashboard behind is worse than it sounds: it sits in the Home
 * Assistant sidebar looking like something is broken, long after the last MCP client
 * exited. Removing it matches how the rest of the bridge behaves - entities are
 * created on demand and cleared when the session that needed them goes away - and it
 * costs nothing, because the next client recreates it.
 */
export async function removeFromDashboard(ha, node, urlPath = DEFAULT_URL_PATH) {
  const socket = await ha.connectSocket();
  try {
    const existing = await socket.send({ type: 'lovelace/config', url_path: urlPath });
    if (!existing.success || !existing.result?.views?.length) return false;

    const config = existing.result;
    const view = config.views[0];
    const cards = (view.cards ?? []).filter(
      (card) => !JSON.stringify(card).includes(`${node}_decision`),
    );
    if (cards.length === (view.cards ?? []).length) return false;

    if (cards.length === 0 && config.views.length === 1) {
      // Look the id up rather than deriving it: Home Assistant stores copilot-mcp as
      // copilot_mcp, and a delete with the wrong form fails with config_not_found.
      const dashboards = await socket.send({ type: 'lovelace/dashboards/list' });
      const entry = (dashboards.result ?? []).find((d) => d.url_path === urlPath);
      if (entry) {
        await socket.send({ type: 'lovelace/dashboards/delete', dashboard_id: entry.id });
        return true;
      }
    }

    await socket.send({
      type: 'lovelace/config/save',
      url_path: urlPath,
      config: { ...config, views: [{ ...view, cards }, ...config.views.slice(1)] },
    });
    return true;
  } finally {
    socket.close();
  }
}
